weather.api.key=d453479811294f87aaa13431260402
spring.application.name=udemy
spring.datasource.url=jdbc:postgresql://localhost:5432/udemy-spring
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.hibernate.ddl-auto=update
## in a production environment, the most efficient way is use 'validate' instead of 'update', it'll just check if java and database mapping are compatible, 
## if they aren't, the app doesn't even start, avoiding the hibernate to change the database structure incorrectly

spring.jpa.show-sql=true
server.error.whitelabel.enabled=false
server.servlet.context-path=/